"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import downloadw9response as shared_downloadw9response
from typing import Optional



@dataclasses.dataclass
class DownloadFormW9Request:
    id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': False }})
    r"""Unique identifier"""
    




@dataclasses.dataclass
class DownloadFormW9Response:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    download_w9_response: Optional[shared_downloadw9response.DownloadW9Response] = dataclasses.field(default=None)
    r"""A file stream for a W9 PDF download."""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

