"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import payableschema as shared_payableschema
from typing import Optional



@dataclasses.dataclass
class CreatePayableOnClientResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    payable_schema: Optional[shared_payableschema.PayableSchema] = dataclasses.field(default=None)
    r"""A payable"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

