"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.shared import checkbookcard as shared_checkbookcard
from ...models.shared import checkbookcardcreate as shared_checkbookcardcreate
from typing import Optional


@dataclasses.dataclass
class CreatePayoutDebitCardRequest:
    member_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'memberId', 'style': 'simple', 'explode': False }})
    r"""Unique identifier of a member"""
    checkbook_card_create: Optional[shared_checkbookcardcreate.CheckbookCardCreate] = dataclasses.field(default=None, metadata={'request': { 'media_type': 'application/json' }})
    



@dataclasses.dataclass
class CreatePayoutDebitCardResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    checkbook_card: Optional[shared_checkbookcard.CheckbookCard] = dataclasses.field(default=None)
    r"""A payout debit card"""
    

