"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import collaboratorevents as shared_collaboratorevents
from typing import Optional



@dataclasses.dataclass
class GetPaymentsCollaboratorIDEventsRequest:
    id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': False }})
    r"""Unique identifier"""
    




@dataclasses.dataclass
class GetPaymentsCollaboratorIDEventsResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    collaborator_events: Optional[shared_collaboratorevents.CollaboratorEvents] = dataclasses.field(default=None)
    r"""List of events on collaborator"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

