"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import payoutsettingsresponse as shared_payoutsettingsresponse
from typing import Optional



@dataclasses.dataclass
class GetPaymentsPayoutSettingsIDRequest:
    id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': False }})
    r"""Unique identifier"""
    




@dataclasses.dataclass
class GetPaymentsPayoutSettingsIDResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    payout_settings_response: Optional[shared_payoutsettingsresponse.PayoutSettingsResponse] = dataclasses.field(default=None)
    r"""The payout settings for a member"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

