"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import carddetails as shared_carddetails
from typing import Optional



@dataclasses.dataclass
class GetCardRequest:
    id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': False }})
    r"""Unique identifier"""
    




@dataclasses.dataclass
class GetCardResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    card_details: Optional[shared_carddetails.CardDetails] = dataclasses.field(default=None)
    r"""A card summary with additional details"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

