"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import clientinvoicetemplate as shared_clientinvoicetemplate
from typing import Optional



@dataclasses.dataclass
class GetClientInvoiceTemplateRequest:
    id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': False }})
    r"""Unique identifier"""
    




@dataclasses.dataclass
class GetClientInvoiceTemplateResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    client_invoice_template: Optional[shared_clientinvoicetemplate.ClientInvoiceTemplate] = dataclasses.field(default=None)
    r"""A client created invoiceTemplate (recurring Invoice)"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

