"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import collaboratorgroupresponse as shared_collaboratorgroupresponse
from typing import Optional



@dataclasses.dataclass
class ListCollaboratorGroupsResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    collaborator_group_responses: Optional[list[shared_collaboratorgroupresponse.CollaboratorGroupResponse]] = dataclasses.field(default=None)
    r"""A list of Collaborator Configurations created by client"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

