"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import clientinvoicetemplate as shared_clientinvoicetemplate
from typing import Optional



@dataclasses.dataclass
class ListClientInvoiceTemplatesResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    client_invoice_templates: Optional[list[shared_clientinvoicetemplate.ClientInvoiceTemplate]] = dataclasses.field(default=None)
    r"""A list of Client Created Invoice Template"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

