"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import bulkpayableitem as shared_bulkpayableitem
from typing import Optional



@dataclasses.dataclass
class ListBulkPayableBatchItemsRequest:
    batch_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'batchId', 'style': 'simple', 'explode': False }})
    r"""Unique identifier for a batch"""
    




@dataclasses.dataclass
class ListBulkPayableBatchItemsResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    bulk_payable_items: Optional[list[shared_bulkpayableitem.BulkPayableItem]] = dataclasses.field(default=None)
    r"""A list of bulk payable items"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    r"""Raw HTTP response; suitable for custom response parsing"""
    

