"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import bulkcollaboratoritem as shared_bulkcollaboratoritem
from typing import Optional



@dataclasses.dataclass
class ListBulkCollaboratorBatchItemsRequest:
    batch_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'batchId', 'style': 'simple', 'explode': False }})
    r"""Unique identifier for a batch"""
    




@dataclasses.dataclass
class ListBulkCollaboratorBatchItemsResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    bulk_collaborator_items: Optional[list[shared_bulkcollaboratoritem.BulkCollaboratorItem]] = dataclasses.field(default=None)
    r"""A list of bulk collaborator items"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

