"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import collaboratorschema as shared_collaboratorschema
from typing import Optional



@dataclasses.dataclass
class ListCollaboratorsResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    collaborator_schemas: Optional[list[shared_collaboratorschema.CollaboratorSchema]] = dataclasses.field(default=None)
    r"""A list of collaborators"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

