"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import clientinvoice as shared_clientinvoice
from typing import Optional



@dataclasses.dataclass
class ListCreatedInvoicesByClientResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    client_invoices: Optional[list[shared_clientinvoice.ClientInvoice]] = dataclasses.field(default=None)
    r"""A list of Client Created Invoices"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

