"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.shared import collaboratorgrouprequirementupdate as shared_collaboratorgrouprequirementupdate
from ...models.shared import collaboratorgroupresponse as shared_collaboratorgroupresponse
from typing import Optional


@dataclasses.dataclass
class ReplaceCollaboratorGroupEligibilityRequirementRequest:
    eligibility_requirement_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'eligibilityRequirementId', 'style': 'simple', 'explode': False }})
    r"""Unique eligibility Requirement Id"""
    id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': False }})
    r"""Unique identifier"""
    collaborator_group_requirement_update: Optional[shared_collaboratorgrouprequirementupdate.CollaboratorGroupRequirementUpdate] = dataclasses.field(default=None, metadata={'request': { 'media_type': 'application/json' }})
    



@dataclasses.dataclass
class ReplaceCollaboratorGroupEligibilityRequirementResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    collaborator_group_response: Optional[shared_collaboratorgroupresponse.CollaboratorGroupResponse] = dataclasses.field(default=None)
    r"""Collaborator Configuration Per Group"""
    

