"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.shared import payableschema as shared_payableschema
from ...models.shared import payableupdaterequest as shared_payableupdaterequest
from typing import Optional


@dataclasses.dataclass
class UpdatePayableOnClientRequest:
    id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': False }})
    r"""Unique identifier"""
    payable_update_request: Optional[shared_payableupdaterequest.PayableUpdateRequest] = dataclasses.field(default=None, metadata={'request': { 'media_type': 'application/json' }})
    



@dataclasses.dataclass
class UpdatePayableOnClientResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    payable_schema: Optional[shared_payableschema.PayableSchema] = dataclasses.field(default=None)
    r"""A payable"""
    

