"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import payrollsettings as shared_payrollsettings
from ..shared import payrollsettingsupdate as shared_payrollsettingsupdate
from typing import Optional


@dataclasses.dataclass
class UpdatePayrollSettingsRequest:
    id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': False }})
    r"""Unique identifier"""
    payroll_settings_update: Optional[shared_payrollsettingsupdate.PayrollSettingsUpdate] = dataclasses.field(default=None, metadata={'request': { 'media_type': 'application/json' }})
    



@dataclasses.dataclass
class UpdatePayrollSettingsResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    payroll_settings: Optional[shared_payrollsettings.PayrollSettings] = dataclasses.field(default=None)
    r"""The payroll settings for a member"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    r"""Raw HTTP response; suitable for custom response parsing"""
    

