"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import bulkinvoicebatch as shared_bulkinvoicebatch
from ..shared import bulkinvoicebatchupdate as shared_bulkinvoicebatchupdate
from typing import Optional



@dataclasses.dataclass
class UpdateBulkInvoiceBatchRequest:
    batch_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'batchId', 'style': 'simple', 'explode': False }})
    r"""Unique identifier for a batch"""
    bulk_invoice_batch_update: Optional[shared_bulkinvoicebatchupdate.BulkInvoiceBatchUpdate] = dataclasses.field(default=None, metadata={'request': { 'media_type': 'application/json' }})
    




@dataclasses.dataclass
class UpdateBulkInvoiceBatchResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    bulk_invoice_batch: Optional[shared_bulkinvoicebatch.BulkInvoiceBatch] = dataclasses.field(default=None)
    r"""A batch of items for importing as invoices"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    r"""Raw HTTP response; suitable for custom response parsing"""
    

