"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import collaboratorgroupresponse as shared_collaboratorgroupresponse
from ..shared import collaboratorgroupupdaterequest as shared_collaboratorgroupupdaterequest
from typing import Optional



@dataclasses.dataclass
class UpdateCollaboratorGroupRequest:
    id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': False }})
    r"""Unique identifier"""
    collaborator_group_update_request: Optional[shared_collaboratorgroupupdaterequest.CollaboratorGroupUpdateRequest] = dataclasses.field(default=None, metadata={'request': { 'media_type': 'application/json' }})
    




@dataclasses.dataclass
class UpdateCollaboratorGroupResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    collaborator_group_response: Optional[shared_collaboratorgroupresponse.CollaboratorGroupResponse] = dataclasses.field(default=None)
    r"""Collaborator Configuration Per Group"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    r"""Raw HTTP response; suitable for custom response parsing"""
    

