"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from enum import Enum
from typing import Any, Optional
from wingspan import utils

class CardProcessingFeesCalculationSettings1099(str, Enum):
    INCLUDE = 'Include'
    EXCLUDE = 'Exclude'
    LESS_THAN_NIL_GREATER_THAN_ = '<nil>'

class OffPlatformPaymentsCalculationSettings1099(str, Enum):
    INCLUDE = 'Include'
    EXCLUDE = 'Exclude'
    LESS_THAN_NIL_GREATER_THAN_ = '<nil>'

class ReimbursableExpensesCalculationSettings1099(str, Enum):
    INCLUDE = 'Include'
    EXCLUDE = 'Exclude'
    LESS_THAN_NIL_GREATER_THAN_ = '<nil>'


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class CalculationSettings1099:
    card_processing_fees: Optional[CardProcessingFeesCalculationSettings1099] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('cardProcessingFees'), 'exclude': lambda f: f is None }})
    off_platform_payments: Optional[OffPlatformPaymentsCalculationSettings1099] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('offPlatformPayments'), 'exclude': lambda f: f is None }})
    reimbursable_expenses: Optional[ReimbursableExpensesCalculationSettings1099] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('reimbursableExpenses'), 'exclude': lambda f: f is None }})
    state_tax_id: Optional[Any] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('stateTaxId'), 'exclude': lambda f: f is None }})
    threshold_amount: Optional[float] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('thresholdAmount'), 'exclude': lambda f: f is None }})
    

