"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from .ce853dbef33b2b91880690c84bc5314340c1301fd7b3503dd6ce79c844e2a481 import Ce853dbef33b2b91880690c84bc5314340c1301fd7b3503dd6ce79c844e2a481
from .eighta9c6cb49482a98cdd603ff09858cdc3e5ef6ad9807c876c4161d925a96694a5 import Eighta9c6cb49482a98cdd603ff09858cdc3e5ef6ad9807c876c4161d925a96694a5
from dataclasses_json import Undefined, dataclass_json
from enum import Enum
from typing import Optional
from wingspan import utils

class DeliveryMethodCollaboratorForm1099BalancesUpdateRequest(str, Enum):
    ELECTRONIC = 'Electronic'
    MAIL = 'Mail'
    BOTH = 'Both'


@dataclasses.dataclass
class Events:
    pass

class StatusCollaboratorForm1099BalancesUpdateRequest(str, Enum):
    READY = 'Ready'
    NEEDS_ACTION_INFO = 'NeedsActionInfo'
    NEEDS_ACTION_DISPUTE = 'NeedsActionDispute'
    SUBMITTED = 'Submitted'
    REJECTED = 'Rejected'
    ACCEPTED = 'Accepted'
    EXCLUDED = 'Excluded'


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class CollaboratorForm1099BalancesUpdateRequest:
    UNSET='__SPEAKEASY_UNSET__'
    adjustments: Optional[float] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('adjustments'), 'exclude': lambda f: f is CollaboratorForm1099BalancesUpdateRequest.UNSET }})
    correction: Optional[Ce853dbef33b2b91880690c84bc5314340c1301fd7b3503dd6ce79c844e2a481] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('correction'), 'exclude': lambda f: f is CollaboratorForm1099BalancesUpdateRequest.UNSET }})
    delivery_method: Optional[DeliveryMethodCollaboratorForm1099BalancesUpdateRequest] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('deliveryMethod'), 'exclude': lambda f: f is CollaboratorForm1099BalancesUpdateRequest.UNSET }})
    dispute: Optional[Eighta9c6cb49482a98cdd603ff09858cdc3e5ef6ad9807c876c4161d925a96694a5] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('dispute'), 'exclude': lambda f: f is CollaboratorForm1099BalancesUpdateRequest.UNSET }})
    events: Optional[Events] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('events'), 'exclude': lambda f: f is CollaboratorForm1099BalancesUpdateRequest.UNSET }})
    status: Optional[StatusCollaboratorForm1099BalancesUpdateRequest] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('status'), 'exclude': lambda f: f is CollaboratorForm1099BalancesUpdateRequest.UNSET }})
    

