"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from typing import Optional
from wingspan import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class FeeHandlingConfig:
    UNSET='__SPEAKEASY_UNSET__'
    client_absolute_percentage: Optional[float] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('clientAbsolutePercentage'), 'exclude': lambda f: f is FeeHandlingConfig.UNSET }})
    client_pays: Optional[float] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('clientPays'), 'exclude': lambda f: f is FeeHandlingConfig.UNSET }})
    member_pays: Optional[float] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('memberPays'), 'exclude': lambda f: f is FeeHandlingConfig.UNSET }})
    

