"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from typing import Any, Optional
from wingspan import utils


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class InvoiceNotificationPreferences:
    send_reminders: bool = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('sendReminders') }})
    send_invoice: Optional[Any] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('sendInvoice'), 'exclude': lambda f: f is None }})
    send_receipt: Optional[Any] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('sendReceipt'), 'exclude': lambda f: f is None }})
    

