"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from enum import Enum
from typing import Optional
from wingspan import utils

class DestinationTypePayoutDestinationUpdate(str, Enum):
    ACCOUNT = 'Account'
    CARD = 'Card'
    WE_GIFT = 'WeGift'

class PayoutMethodPayoutDestinationUpdate(str, Enum):
    STANDARD = 'Standard'
    INSTANT = 'Instant'
    EXPEDITED = 'Expedited'
    CHECK = 'Check'
    E_CHECK = 'ECheck'


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class PayoutDestinationUpdate:
    UNSET='__SPEAKEASY_UNSET__'
    destination_id: Optional[str] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('destinationId'), 'exclude': lambda f: f is PayoutDestinationUpdate.UNSET }})
    destination_type: Optional[DestinationTypePayoutDestinationUpdate] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('destinationType'), 'exclude': lambda f: f is PayoutDestinationUpdate.UNSET }})
    payout_method: Optional[PayoutMethodPayoutDestinationUpdate] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('payoutMethod'), 'exclude': lambda f: f is PayoutDestinationUpdate.UNSET }})
    percentage: Optional[float] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('percentage'), 'exclude': lambda f: f is PayoutDestinationUpdate.UNSET }})
    

