"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import redacteduser as shared_redacteduser
from ..shared import twenty_threed776fc12e56286a20f36065e4f942c43a28218a62eb2f211116c130deb74eb as shared_twenty_threed776fc12e56286a20f36065e4f942c43a28218a62eb2f211116c130deb74eb
from dataclasses_json import Undefined, dataclass_json
from typing import Optional
from wingspan import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class RedactedMember:
    user: shared_redacteduser.RedactedUser = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('user') }})
    profile: Optional[shared_twenty_threed776fc12e56286a20f36065e4f942c43a28218a62eb2f211116c130deb74eb.TwentyThreed776fc12e56286a20f36065e4f942c43a28218a62eb2f211116c130deb74eb] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('profile') }})
    

