"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from typing import Any, Optional
from wingspan import utils


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class Twelved9f9a45dd678e21e49e960084c87d9e541aadd0c26b6e676a00139e89b6915:
    form1099_filings: Optional[Any] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('form1099Filings'), 'exclude': lambda f: f is None }})
    form_w9_document: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('formW9Document'), 'exclude': lambda f: f is None }})
    previous_temporary_track_user_ids: Optional[list[str]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('previousTemporaryTrackUserIds'), 'exclude': lambda f: f is None }})
    temporary_track_user_id: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('temporaryTrackUserId'), 'exclude': lambda f: f is None }})
    

